### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by mocheaz** [cangelis/l4pdf#10] opened 2014-04-27 07:20 UTC
I'm receiving this error after installing 0.12 on ubuntu 13.10:
PDF could not be created: "Segmentation fault (core dumped)\n"

It worked good with 0.11on ubuntu 12.04.

What's wrong?

**Comment by cangelis** [comment] 2014-04-28 15:55
This must be caused by `wkhtmltopdf` executable. I think you should open an issue on [wkhtmltopdf Repo](https://github.com/wkhtmltopdf/wkhtmltopdf)

**Comment by cangelis** [comment] 2014-08-11 22:29
I'm closing the issue since looks like there's nothing to do with php-side. Please reopen the issue if you think we have something we can do.

**Closed as completed by cangelis** 2014-08-11 22:29 UTC
